name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: restore cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: deps and run tests
        run: |
          lerna bootstrap
          cd commit-editor-app
          npm test -- --collectCoverage

      - name: prepare coverage report
        run: |
          mkdir coverage
          cat commit-editor-app/coverage/lcov.info | sed 's/^SF:/SF:commit-editor-app\//g' > coverage/lcov.info

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
